FROM ubuntu:20.04

RUN apt-get update && apt-get install -y hostapd iptables bridge-utils

# Copy the specific hostapd configuration file for WPA2 network with no client
COPY hostapd-wpa2-2.conf /etc/hostapd/hostapd.conf

# Start hostapd when the container runs
CMD ["hostapd", "/etc/hostapd/hostapd.conf"]
